import type { SessionDefinition } from '../../../masterclass-engine/types'

export const mc10Session07: SessionDefinition = {
  id: 'mc10-session-07',
  number: 7,
  stage: 'discover',
  title: 'Observability & Production Operations - Seeing a Distributed System',
  objective:
    'Understand metrics, logs, distributed traces, correlation identifiers, health checks, SLIs, SLOs, alerting and incident response for production distributed systems.',
  experiences: [
    {
      id: 'mc10-s07-observability-lesson',
      type: 'lesson',
      title: 'How to Understand a Distributed System in Production',
      description:
        'Learn how engineering teams observe distributed applications and investigate problems across multiple services.',
      lesson: {
        opening:
          'A distributed system can fail in places that are invisible from one service alone. Production observability gives the team enough evidence to understand what happened, where it happened and how users were affected.',
        sections: [
          {
            heading: '1. Observability versus monitoring',
            explanation:
              'Monitoring usually focuses on known signals and expected conditions. Observability is the ability to understand internal system behavior from available external signals.',
            example:
              'An EDDUU dashboard can alert when error rate is high, while distributed tracing can help explain which downstream service caused the errors.',
          },
          {
            heading: '2. Metrics',
            explanation:
              'Metrics are numerical measurements collected over time. They are useful for identifying trends, thresholds and changes in system behavior.',
            example:
              'EDDUU can measure request rate, error rate, response latency, CPU usage and queue depth.',
          },
          {
            heading: '3. The four golden signals',
            explanation:
              'A common reliability view focuses on latency, traffic, errors and saturation. These signals help teams understand demand, performance and resource pressure.',
            example:
              'A sudden increase in EDDUU API latency together with high CPU saturation can indicate resource pressure.',
          },
          {
            heading: '4. Logs',
            explanation:
              'Logs record discrete application or infrastructure events. Structured logs make it easier to search and correlate events across services.',
            example:
              'An EDDUU service can record request identifiers, operation names, status values and failure details in structured log fields.',
          },
          {
            heading: '5. Correlation identifiers',
            explanation:
              'A correlation identifier allows related work to be connected across multiple services. This is especially useful when one user request creates many downstream operations.',
            example:
              'An EDDUU request can receive a correlation ID that is included in logs generated by the Dashboard, Learning and Profile services.',
          },
          {
            heading: '6. Distributed tracing',
            explanation:
              'A distributed trace represents one logical request as it travels through multiple services. Individual spans show the work performed by each component.',
            example:
              'An EDDUU trace can show that the Dashboard waited 40 milliseconds for Profile Service and 600 milliseconds for Recommendation Service.',
          },
          {
            heading: '7. Trace and span',
            explanation:
              'A trace represents the overall distributed operation. A span represents one timed operation within that trace.',
            example:
              'The EDDUU dashboard request can be the trace while calls to Profile, Learning and Recommendation are individual spans.',
          },
          {
            heading: '8. Health checks',
            explanation:
              'Health endpoints provide machine-readable signals about service state. Liveness can indicate that a process is running, while readiness can indicate whether it should receive traffic.',
            example:
              'A new EDDUU service instance can remain out of production traffic until its readiness check succeeds.',
          },
          {
            heading: '9. SLIs',
            explanation:
              'A Service Level Indicator is a measurable signal representing an aspect of service behavior such as availability or latency.',
            example:
              'EDDUU can define successful request percentage as an availability-related SLI.',
          },
          {
            heading: '10. SLOs',
            explanation:
              'A Service Level Objective defines a target for an SLI over a specified period.',
            example:
              'EDDUU might define an objective that a high percentage of eligible API requests complete successfully within the target latency.',
          },
          {
            heading: '11. Error budgets',
            explanation:
              'An error budget represents the amount of unreliability allowed by an SLO during a period. It helps teams balance reliability work with feature delivery.',
            example:
              'If EDDUU consumes too much of its reliability budget, leadership may prioritize reliability improvements before additional risky releases.',
          },
          {
            heading: '12. Alerting',
            explanation:
              'Alerts should identify conditions that require action rather than notifying engineers about every unusual measurement.',
            example:
              'A sustained increase in user-facing errors is more actionable than a brief harmless CPU spike.',
          },
          {
            heading: '13. Queue and messaging observability',
            explanation:
              'Event-driven systems require visibility into queue depth, consumer lag, processing time, retry counts and dead-letter messages.',
            example:
              'EDDUU can detect that Analytics consumers are falling behind by observing increasing message lag.',
          },
          {
            heading: '14. Incident response',
            explanation:
              'An incident response process gives the team a structured way to detect, assess, mitigate, communicate and recover from production problems.',
            example:
              'During an EDDUU outage, the team can first stabilize the user-facing platform before investigating the deeper root cause.',
          },
          {
            heading: '15. Mitigation before root cause',
            explanation:
              'During an active incident, restoring service can be more urgent than finding the final root cause. Root-cause analysis can continue after the system is stable.',
            example:
              'EDDUU can temporarily disable a non-critical feature to reduce load while engineers investigate the failing dependency.',
          },
          {
            heading: '16. Post-incident learning',
            explanation:
              'A useful post-incident review identifies contributing factors, detection gaps, response improvements and concrete follow-up actions.',
            example:
              'After an EDDUU incident, the team can improve alerting, capacity planning or dependency isolation based on what the incident revealed.',
          },
        ],
        realWorldConnection:
          'Production observability connects technical signals with user impact. Strong teams use metrics, logs and traces together rather than depending on a single monitoring dashboard.',
        keyIdea:
          'Observability gives engineers evidence about what the distributed system is doing, while operations turns that evidence into detection, mitigation and continuous improvement.',
        recap: [
          'Metrics show numerical system behavior over time.',
          'Logs record discrete events and diagnostic context.',
          'Correlation IDs connect related operations.',
          'Distributed traces show requests across service boundaries.',
          'Spans show individual operations within a trace.',
          'Health checks help control service traffic.',
          'SLIs measure important service behavior.',
          'SLOs define measurable reliability targets.',
          'Alerts should focus on actionable conditions.',
          'Incident response prioritizes stabilization and controlled recovery.',
        ],
      },
    },

    {
      id: 'mc10-s07-observability-animation',
      type: 'animation',
      title: 'Trace One EDDUU Request Across Services',
      description:
        'Follow one user request through multiple services while observing the correlation ID, metrics, logs and distributed trace.',
      animation: {
        visual: 'architecture',
        opening:
          'A single EDDUU request can cross several service boundaries. Observability connects those individual operations into one production story.',
        parts: [
          {
            id: 'request-entry',
            label: 'REQUEST ENTERS EDDUU',
            explanation:
              'The user request enters the platform and receives a correlation identifier.',
            example:
              'The Dashboard API creates correlation ID req-4821 for the request.',
          },
          {
            id: 'dashboard-span',
            label: 'DASHBOARD SPAN',
            explanation:
              'The first span records the time spent handling the dashboard operation.',
            example:
              'The trace records the Dashboard API processing span.',
          },
          {
            id: 'learning-span',
            label: 'LEARNING SERVICE SPAN',
            explanation:
              'The trace follows a downstream call into the Learning Service.',
            example:
              'The Learning Service span records its request duration and result.',
          },
          {
            id: 'profile-span',
            label: 'PROFILE SERVICE SPAN',
            explanation:
              'Another downstream call appears as another span under the same trace.',
            example:
              'The Profile Service span shows profile retrieval latency.',
          },
          {
            id: 'slow-dependency',
            label: 'SLOW DEPENDENCY',
            explanation:
              'One downstream span becomes significantly slower than the others.',
            example:
              'Recommendation Service takes 900 milliseconds while the other services respond quickly.',
          },
          {
            id: 'logs',
            label: 'CORRELATED LOGS',
            explanation:
              'Structured logs containing the correlation ID connect service events to the same request.',
            example:
              'Operations can search req-4821 across multiple service logs.',
          },
          {
            id: 'metrics',
            label: 'SERVICE METRICS',
            explanation:
              'Metrics reveal whether the slow behavior is isolated or affecting a wider percentage of traffic.',
            example:
              'Recommendation latency and dashboard latency both increase during the incident.',
          },
          {
            id: 'alert',
            label: 'ACTIONABLE ALERT',
            explanation:
              'An alert fires when the observed condition crosses an operational threshold that requires attention.',
            example:
              'The API latency SLO begins to breach its target.',
          },
        ],
        closing:
          'The trace shows where the request spent time, logs provide diagnostic context and metrics reveal whether the problem is isolated or systemic.',
      },
    },

    {
      id: 'mc10-s07-observability-simulation',
      type: 'simulation',
      title: 'Investigate the EDDUU Production Incident',
      description:
        'Use production signals to identify the most useful next investigation step.',
      simulation: {
        instruction:
          'Match each production symptom with the observability signal or operational action that best helps investigate it.',
        items: [
          {
            id: 'latency-spike',
            label:
              'User-facing API latency suddenly increases across several endpoints.',
            description:
              'The team needs to determine which downstream operation is consuming time.',
            correctTargetId: 'distributed-trace',
          },
          {
            id: 'error-context',
            label:
              'One service returns errors and the team needs request-specific diagnostic context.',
            description:
              'The investigation needs searchable event details connected to the request.',
            correctTargetId: 'structured-logs',
          },
          {
            id: 'broad-impact',
            label:
              'The team needs to determine whether a latency problem affects a small percentage or most requests.',
            description:
              'A numerical signal over time is required.',
            correctTargetId: 'metrics',
          },
          {
            id: 'queue-growth',
            label:
              'Analytics processing is falling behind and messages are accumulating.',
            description:
              'The team needs visibility into asynchronous processing pressure.',
            correctTargetId: 'queue-metrics',
          },
          {
            id: 'active-outage',
            label:
              'A critical dependency is causing user-facing failures during an active incident.',
            description:
              'The immediate priority is to restore stable service.',
            correctTargetId: 'mitigate-first',
          },
        ],
        targets: [
          {
            id: 'distributed-trace',
            label: 'DISTRIBUTED TRACE',
            description:
              'Follow one request across service boundaries and identify slow spans.',
          },
          {
            id: 'structured-logs',
            label: 'STRUCTURED LOGS',
            description:
              'Search detailed request and service events using shared identifiers.',
          },
          {
            id: 'metrics',
            label: 'METRICS',
            description:
              'Measure trends, rates, latency and the percentage of affected traffic.',
          },
          {
            id: 'queue-metrics',
            label: 'QUEUE METRICS',
            description:
              'Inspect queue depth, consumer lag and processing pressure.',
          },
          {
            id: 'mitigate-first',
            label: 'MITIGATE FIRST',
            description:
              'Stabilize user-facing service before completing deeper root-cause analysis.',
          },
        ],
        successMessage:
          'Excellent. Production investigation works best when metrics, logs and traces are combined with disciplined incident response.',
        failureMessage:
          'Ask whether you need request path, detailed event context, broad numerical impact, queue pressure or immediate service stabilization.',
      },
    },

    {
      id: 'mc10-s07-observability-question',
      type: 'question',
      title: 'Observability Architecture Check',
      description:
        'Check whether you can select the right observability signal for a distributed-system investigation.',
      question: {
        id: 'mc10-s07-observability',
        type: 'single-choice',
        question:
          'An EDDUU request is slow, and the team needs to know which downstream service consumed most of the request time. What is the most useful first signal?',
        options: [
          {
            id: 'trace',
            text:
              'A distributed trace showing the spans and duration of downstream calls.',
            correct: true,
          },
          {
            id: 'cpu-only',
            text:
              'CPU usage from one unrelated service only.',
            correct: false,
          },
          {
            id: 'source-code',
            text:
              'The source code without production request context.',
            correct: false,
          },
          {
            id: 'deployment-count',
            text:
              'The number of deployments made during the month.',
            correct: false,
          },
        ],
        explanation:
          'A distributed trace connects one logical request across service boundaries and shows the duration of individual spans, making it especially useful for locating latency within a request path.',
        hints: [
          'The question asks where one request spent its time.',
          'Look for the signal that follows a request across services.',
        ],
      },
    },
  ],
}