import type { KnowledgeDefinition } from './knowledge'

export const opentelemetryKnowledge: KnowledgeDefinition = {
  technologyId: 'opentelemetry',
  slug: 'opentelemetry',
  title: 'OpenTelemetry',
  summary:
    'OpenTelemetry is an open-source observability framework for generating, collecting, processing, and exporting telemetry such as traces, metrics, and logs using standardized APIs, SDKs, and semantic conventions.',
  difficulty: 'advanced',

  sections: [
    {
      title: 'What is OpenTelemetry?',
      content:
        'OpenTelemetry, commonly called OTel, is an open-source observability framework and ecosystem that provides standardized ways for applications to generate and export telemetry. It supports traces, metrics, and logs and is designed to reduce tight coupling between application instrumentation and a specific observability vendor.',
      highlights: [
        {
          title: 'OpenTelemetry',
          description:
            'An open-source framework and ecosystem for application telemetry.',
        },
        {
          title: 'Telemetry',
          description:
            'Operational data such as metrics, logs, and traces generated by software systems.',
        },
        {
          title: 'Vendor-neutral',
          description:
            'Designed so telemetry can be exported to different compatible observability backends.',
        },
      ],
    },

    {
      title: 'Simple Analogy',
      content:
        'Think of OpenTelemetry like a universal adapter for observability. Your application produces information about what it is doing. Instead of building a different connection for every monitoring company, OpenTelemetry provides a standard way to generate and move that information to the observability system you choose.',
      highlights: [
        {
          title: 'Application',
          description:
            'The source producing operational information.',
        },
        {
          title: 'Universal adapter',
          description:
            'Represents the standardized OpenTelemetry instrumentation and data model.',
        },
        {
          title: 'Backend',
          description:
            'The observability platform receiving the exported telemetry.',
        },
      ],
    },

    {
      title: 'Why OpenTelemetry Matters',
      content:
        'Modern systems use multiple services, cloud platforms, databases, queues, AI providers, and infrastructure components. Without standardized telemetry, every team may instrument systems differently. OpenTelemetry provides common concepts and APIs that make observability more consistent across an organization.',
      highlights: [
        {
          title: 'Standardization',
          description:
            'Provides common APIs, SDKs, and conventions for telemetry.',
        },
        {
          title: 'Portability',
          description:
            'Makes it easier to change or use multiple observability backends.',
        },
        {
          title: 'Cross-service visibility',
          description:
            'Helps connect telemetry across distributed applications.',
        },
      ],
    },

    {
      title: 'OpenTelemetry and the Three Signals',
      content:
        'OpenTelemetry supports the major observability signals: traces, metrics, and logs. These signals answer different questions and become more powerful when correlated.',
      highlights: [
        {
          title: 'Traces',
          description:
            'Show the path of individual requests through distributed systems.',
        },
        {
          title: 'Metrics',
          description:
            'Provide aggregated numerical measurements over time.',
        },
        {
          title: 'Logs',
          description:
            'Provide detailed records of application and infrastructure events.',
        },
      ],
    },

    {
      title: 'OpenTelemetry API',
      content:
        'The OpenTelemetry API provides interfaces that application code and instrumentation libraries can use to create and interact with telemetry. The API is separated conceptually from the implementation so instrumentation can remain decoupled from telemetry processing details.',
      highlights: [
        {
          title: 'API',
          description:
            'Interfaces used by application code and instrumentation to interact with OpenTelemetry.',
        },
        {
          title: 'Instrumentation',
          description:
            'Code or libraries that create telemetry around application operations.',
        },
        {
          title: 'Decoupling',
          description:
            'Keeping application instrumentation separate from the telemetry backend implementation.',
        },
      ],
    },

    {
      title: 'OpenTelemetry SDK',
      content:
        'The OpenTelemetry SDK provides the implementation that processes telemetry generated through the API. It can configure exporters, sampling, resource information, processors, and other runtime behavior.',
      highlights: [
        {
          title: 'SDK',
          description:
            'The implementation layer that handles telemetry processing and export.',
        },
        {
          title: 'Exporter',
          description:
            'A component that sends telemetry to an external destination.',
        },
        {
          title: 'Processor',
          description:
            'A component that processes telemetry before export.',
        },
      ],
    },

    {
      title: 'API vs SDK',
      content:
        'A simple way to think about the separation is that the API defines how application code interacts with telemetry, while the SDK provides the actual implementation and configuration used to process and export that telemetry.',
      highlights: [
        {
          title: 'API',
          description:
            'Defines interfaces and contracts.',
        },
        {
          title: 'SDK',
          description:
            'Provides implementation and runtime configuration.',
        },
        {
          title: 'Benefit',
          description:
            'The separation helps keep application instrumentation more portable.',
        },
      ],
    },

    {
      title: 'OpenTelemetry Collector',
      content:
        'The OpenTelemetry Collector is a vendor-neutral component that can receive, process, and export telemetry. It allows applications and infrastructure to send telemetry to a central processing layer before the data reaches one or more observability backends.',
      highlights: [
        {
          title: 'Collector',
          description:
            'A service that receives, processes, and exports telemetry.',
        },
        {
          title: 'Receiver',
          description:
            'A Collector component that accepts telemetry from sources.',
        },
        {
          title: 'Processor',
          description:
            'A Collector component that transforms, filters, batches, or otherwise processes telemetry.',
        },
        {
          title: 'Exporter',
          description:
            'A Collector component that sends telemetry to a destination.',
        },
      ],
    },

    {
      title: 'Collector Architecture',
      content:
        'A typical Collector pipeline contains receivers, processors, and exporters. Telemetry enters through a receiver, passes through configured processors, and is then sent to one or more exporters. Different pipelines can be configured for traces, metrics, and logs.',
      highlights: [
        {
          title: 'Receiver',
          description:
            'Accepts incoming telemetry.',
        },
        {
          title: 'Processor',
          description:
            'Modifies, filters, batches, samples, or enriches telemetry.',
        },
        {
          title: 'Exporter',
          description:
            'Sends processed telemetry to a backend or another telemetry destination.',
        },
      ],
    },

    {
      title: 'Agent vs Gateway Collector',
      content:
        'A Collector can run close to applications as an agent or as a centralized gateway. Agent-style deployments collect telemetry locally from workloads, while gateway-style deployments provide a shared processing and routing layer.',
      highlights: [
        {
          title: 'Agent',
          description:
            'A Collector deployed close to workloads or hosts.',
        },
        {
          title: 'Gateway',
          description:
            'A centralized Collector layer that receives telemetry from multiple sources.',
        },
        {
          title: 'Hybrid architecture',
          description:
            'A design using local agents and centralized gateway collectors together.',
        },
      ],
    },

    {
      title: 'OTLP',
      content:
        'OTLP, the OpenTelemetry Protocol, is a protocol designed for transmitting OpenTelemetry telemetry. It supports communication between instrumentation, Collectors, and compatible observability backends.',
      highlights: [
        {
          title: 'OTLP',
          description:
            'The OpenTelemetry Protocol used to transport telemetry.',
        },
        {
          title: 'Telemetry transport',
          description:
            'The mechanism used to move observability data between components.',
        },
        {
          title: 'Interoperability',
          description:
            'The ability of different telemetry components to communicate using a common protocol.',
        },
      ],
    },

    {
      title: 'Traces in OpenTelemetry',
      content:
        'OpenTelemetry provides APIs and SDKs for creating traces and spans. A trace represents a logical operation, while spans represent individual units of work. Trace context can be propagated across services so distributed operations remain connected.',
      highlights: [
        {
          title: 'Trace',
          description:
            'The complete representation of a logical distributed operation.',
        },
        {
          title: 'Span',
          description:
            'A timed unit of work within a trace.',
        },
        {
          title: 'Trace context',
          description:
            'Metadata used to connect spans across service boundaries.',
        },
      ],
    },

    {
      title: 'Spans',
      content:
        'Spans can represent HTTP requests, database queries, message processing, external API calls, model invocations, or business operations. They contain timing and contextual information used to understand distributed request behavior.',
      highlights: [
        {
          title: 'Span name',
          description:
            'A meaningful name describing the operation.',
        },
        {
          title: 'Span attributes',
          description:
            'Metadata describing the operation and its context.',
        },
        {
          title: 'Span events',
          description:
            'Timestamped events recorded within the lifetime of a span.',
        },
      ],
    },

    {
      title: 'Context Propagation',
      content:
        'Context propagation allows trace information to travel from one service or process to another. When Service A calls Service B, OpenTelemetry propagation allows Service B to continue the same trace instead of creating an unrelated trace.',
      highlights: [
        {
          title: 'Propagation',
          description:
            'Passing telemetry context across boundaries.',
        },
        {
          title: 'Distributed trace',
          description:
            'A connected trace spanning multiple services.',
        },
        {
          title: 'Correlation',
          description:
            'Maintaining relationships between related operations.',
        },
      ],
    },

    {
      title: 'W3C Trace Context',
      content:
        'OpenTelemetry commonly uses W3C Trace Context for HTTP trace propagation. Standardized propagation makes it easier for independently developed services and telemetry libraries to preserve trace relationships.',
      highlights: [
        {
          title: 'W3C Trace Context',
          description:
            'A standard for propagating distributed tracing context.',
        },
        {
          title: 'traceparent',
          description:
            'A standard HTTP header used to carry trace context.',
        },
        {
          title: 'Interoperability',
          description:
            'The ability of different services and tracing implementations to understand the same context.',
        },
      ],
    },

    {
      title: 'Metrics in OpenTelemetry',
      content:
        'OpenTelemetry supports generating and exporting application and infrastructure metrics. Metrics can represent counters, gauges, histograms, and other measurements used for monitoring and SLO calculations.',
      highlights: [
        {
          title: 'Counter',
          description:
            'A cumulative measurement of events.',
        },
        {
          title: 'Gauge',
          description:
            'A measurement representing a value that can increase or decrease.',
        },
        {
          title: 'Histogram',
          description:
            'A measurement representing the distribution of observed values.',
        },
      ],
    },

    {
      title: 'Logs in OpenTelemetry',
      content:
        'OpenTelemetry also provides a standardized approach to logging telemetry. Logs can carry contextual information such as trace and span identifiers, allowing detailed events to be correlated with distributed traces.',
      highlights: [
        {
          title: 'Log record',
          description:
            'A structured record representing an application or system event.',
        },
        {
          title: 'Trace correlation',
          description:
            'Associating logs with the trace and span that generated the event.',
        },
        {
          title: 'Structured telemetry',
          description:
            'Telemetry represented in a consistent machine-readable format.',
        },
      ],
    },

    {
      title: 'Resource Attributes',
      content:
        'OpenTelemetry associates telemetry with resource information describing the entity producing it. Examples include service name, service version, deployment environment, host, container, or Kubernetes workload information.',
      highlights: [
        {
          title: 'Resource',
          description:
            'The entity associated with generated telemetry.',
        },
        {
          title: 'Service name',
          description:
            'The logical name identifying the service producing telemetry.',
        },
        {
          title: 'Service version',
          description:
            'The deployed version associated with telemetry.',
        },
      ],
    },

    {
      title: 'Semantic Conventions',
      content:
        'Semantic conventions provide standardized names and meanings for telemetry attributes. Consistent conventions make telemetry easier to query, compare, visualize, and correlate across different applications and teams.',
      highlights: [
        {
          title: 'Semantic convention',
          description:
            'A standardized definition for telemetry attributes and their meanings.',
        },
        {
          title: 'Consistency',
          description:
            'Using the same attribute names and meanings across services.',
        },
        {
          title: 'Interoperability',
          description:
            'Making telemetry easier for different tools and teams to understand.',
        },
      ],
    },

    {
      title: 'Instrumentation',
      content:
        'Instrumentation is the process of adding telemetry generation to an application. OpenTelemetry supports both automatic instrumentation for supported frameworks and libraries and manual instrumentation for custom business operations.',
      highlights: [
        {
          title: 'Instrumentation',
          description:
            'Adding telemetry generation to software.',
        },
        {
          title: 'Automatic instrumentation',
          description:
            'Telemetry generated by supported instrumentation libraries with limited application changes.',
        },
        {
          title: 'Manual instrumentation',
          description:
            'Explicitly creating telemetry around custom application operations.',
        },
      ],
    },

    {
      title: 'Automatic Instrumentation',
      content:
        'Automatic instrumentation can create telemetry around common frameworks, HTTP servers, clients, database libraries, and messaging systems. It reduces the amount of custom instrumentation developers need to write.',
      highlights: [
        {
          title: 'Automatic instrumentation',
          description:
            'Prebuilt instrumentation that generates telemetry for supported technologies.',
        },
        {
          title: 'Framework coverage',
          description:
            'The set of application frameworks and libraries supported by instrumentation.',
        },
        {
          title: 'Reduced code changes',
          description:
            'Less application-specific instrumentation code is required.',
        },
      ],
    },

    {
      title: 'Manual Instrumentation',
      content:
        'Manual instrumentation is useful when automatic instrumentation does not capture an important business operation. Teams can create spans, metrics, or logs around meaningful workflows such as payment processing, AI orchestration, document retrieval, or lead qualification.',
      highlights: [
        {
          title: 'Business operation',
          description:
            'A meaningful domain-level operation worth observing.',
        },
        {
          title: 'Custom span',
          description:
            'A manually created span representing application-specific work.',
        },
        {
          title: 'Business telemetry',
          description:
            'Operational signals connected directly to business workflows.',
        },
      ],
    },

    {
      title: 'Sampling',
      content:
        'OpenTelemetry can participate in trace sampling so teams do not need to retain every trace. Sampling helps control telemetry volume and cost while preserving useful information for troubleshooting and reliability analysis.',
      highlights: [
        {
          title: 'Sampling',
          description:
            'Selecting which telemetry, especially traces, should be retained or exported.',
        },
        {
          title: 'Head sampling',
          description:
            'Making a sampling decision early in the trace lifecycle.',
        },
        {
          title: 'Tail sampling',
          description:
            'Selecting traces after more information about the complete trace is available.',
        },
      ],
    },

    {
      title: 'Processors',
      content:
        'OpenTelemetry processors can transform or manage telemetry before export. Depending on the deployment, processors can batch data, add or remove attributes, filter telemetry, sample traces, and control resource usage.',
      highlights: [
        {
          title: 'Batch processor',
          description:
            'Groups telemetry into batches to improve export efficiency.',
        },
        {
          title: 'Filter',
          description:
            'Removes telemetry that does not meet defined criteria.',
        },
        {
          title: 'Attribute processor',
          description:
            'Adds, updates, or removes telemetry attributes.',
        },
      ],
    },

    {
      title: 'Batching',
      content:
        'Batching combines multiple telemetry records before sending them to a backend. This can reduce network overhead and improve export efficiency, especially in high-throughput systems.',
      highlights: [
        {
          title: 'Batch',
          description:
            'A group of telemetry records exported together.',
        },
        {
          title: 'Throughput',
          description:
            'The amount of telemetry processed over time.',
        },
        {
          title: 'Network efficiency',
          description:
            'Reducing per-record communication overhead through batching.',
        },
      ],
    },

    {
      title: 'OpenTelemetry Exporters',
      content:
        'Exporters send telemetry from the OpenTelemetry SDK or Collector to an observability backend. Export targets may include compatible monitoring, logging, tracing, or telemetry platforms.',
      highlights: [
        {
          title: 'Exporter',
          description:
            'A component responsible for sending telemetry to a destination.',
        },
        {
          title: 'Backend',
          description:
            'The system that stores, queries, visualizes, or analyzes telemetry.',
        },
        {
          title: 'Vendor neutrality',
          description:
            'Applications can use standardized telemetry while changing compatible backends.',
        },
      ],
    },

    {
      title: 'OpenTelemetry and Prometheus',
      content:
        'OpenTelemetry and Prometheus can work together. OpenTelemetry can generate and process telemetry, while Prometheus can serve as a metrics backend in architectures that support compatible metric ingestion or scraping patterns. Teams should choose the integration model according to their architecture and operational requirements.',
      highlights: [
        {
          title: 'OpenTelemetry',
          description:
            'Provides standardized telemetry instrumentation and collection capabilities.',
        },
        {
          title: 'Prometheus',
          description:
            'Provides metrics collection, storage, and PromQL querying.',
        },
        {
          title: 'Integration',
          description:
            'The two technologies can participate in the same observability architecture.',
        },
      ],
    },

    {
      title: 'OpenTelemetry and Grafana',
      content:
        'Grafana can visualize telemetry produced through OpenTelemetry when the telemetry is exported to compatible data sources. This allows teams to build dashboards and investigation workflows around standardized instrumentation.',
      highlights: [
        {
          title: 'Grafana',
          description:
            'Provides visualization and observability interfaces.',
        },
        {
          title: 'OpenTelemetry',
          description:
            'Provides standardized telemetry generation and collection.',
        },
        {
          title: 'Observability pipeline',
          description:
            'The path telemetry follows from application instrumentation to an analysis interface.',
        },
      ],
    },

    {
      title: 'OpenTelemetry in Microservices',
      content:
        'OpenTelemetry is particularly useful in microservices because requests frequently cross many service boundaries. Standardized propagation and instrumentation allow teams to maintain a connected view of the complete request path.',
      highlights: [
        {
          title: 'Service boundary',
          description:
            'A boundary between independently operating services.',
        },
        {
          title: 'Cross-service trace',
          description:
            'A trace spanning multiple services.',
        },
        {
          title: 'Dependency visibility',
          description:
            'Understanding how services depend on one another.',
        },
      ],
    },

    {
      title: 'OpenTelemetry in Kubernetes',
      content:
        'Kubernetes environments contain dynamic workloads and frequently changing service instances. OpenTelemetry Collectors can be deployed as agents or gateways to collect telemetry from applications, containers, and infrastructure while applying consistent processing and export policies.',
      highlights: [
        {
          title: 'Collector agent',
          description:
            'A Collector deployed close to Kubernetes workloads.',
        },
        {
          title: 'Collector gateway',
          description:
            'A centralized Collector layer that processes telemetry from multiple workloads.',
        },
        {
          title: 'Dynamic workload',
          description:
            'A workload whose instances can be created, removed, or rescheduled automatically.',
        },
      ],
    },

    {
      title: 'OpenTelemetry for AI Applications',
      content:
        'AI applications can use OpenTelemetry to trace model calls, retrieval operations, tool invocations, external providers, database access, and application workflows. This helps teams understand end-to-end latency, failures, and resource consumption.',
      highlights: [
        {
          title: 'Model span',
          description:
            'A span representing an AI model invocation.',
        },
        {
          title: 'Retrieval span',
          description:
            'A span representing retrieval of context or knowledge.',
        },
        {
          title: 'Tool span',
          description:
            'A span representing an agent or application tool invocation.',
        },
      ],
    },

    {
      title: 'OpenTelemetry for RAG',
      content:
        'A RAG application can use OpenTelemetry to trace query processing, embedding generation, vector retrieval, reranking, prompt construction, model generation, and response processing. This creates a connected view of the complete retrieval and generation pipeline.',
      highlights: [
        {
          title: 'Embedding operation',
          description:
            'The process of generating vector representations for text or other content.',
        },
        {
          title: 'Vector retrieval',
          description:
            'The operation that finds relevant knowledge from a vector index.',
        },
        {
          title: 'Generation',
          description:
            'The model operation that produces the final response.',
        },
      ],
    },

    {
      title: 'OpenTelemetry for AI Voice',
      content:
        'An AI voice platform can use OpenTelemetry to connect call setup, speech recognition, model reasoning, tool calls, text-to-speech, telephony providers, and post-call processing into one observable workflow.',
      highlights: [
        {
          title: 'Call trace',
          description:
            'A trace representing the lifecycle of a voice interaction.',
        },
        {
          title: 'STT span',
          description:
            'A span representing speech-to-text processing.',
        },
        {
          title: 'TTS span',
          description:
            'A span representing text-to-speech processing.',
        },
      ],
    },

    {
      title: 'OpenTelemetry and Error Diagnosis',
      content:
        'OpenTelemetry can attach error information to spans and correlate errors with traces and logs. This makes it easier to identify the operation that failed and understand which upstream requests were affected.',
      highlights: [
        {
          title: 'Error span',
          description:
            'A span containing information about a failed operation.',
        },
        {
          title: 'Exception',
          description:
            'An abnormal execution condition associated with an operation.',
        },
        {
          title: 'Error correlation',
          description:
            'Connecting error information with related traces and logs.',
        },
      ],
    },

    {
      title: 'OpenTelemetry and Privacy',
      content:
        'Telemetry can accidentally expose sensitive information. AI applications are especially important because prompts, retrieved documents, user information, model responses, and provider metadata may contain confidential data. Instrumentation should follow data minimization, redaction, access control, and retention policies.',
      highlights: [
        {
          title: 'Data minimization',
          description:
            'Collecting only the telemetry necessary for operational purposes.',
        },
        {
          title: 'Redaction',
          description:
            'Removing or masking sensitive values before telemetry is stored or exported.',
        },
        {
          title: 'Retention policy',
          description:
            'Defining how long telemetry should be retained.',
        },
      ],
    },

    {
      title: 'OpenTelemetry Cost Management',
      content:
        'Telemetry volume can become significant in large systems. Cost can be controlled through sampling, batching, filtering, attribute management, retention policies, and appropriate Collector architecture.',
      highlights: [
        {
          title: 'Sampling',
          description:
            'Reducing the amount of telemetry retained or exported.',
        },
        {
          title: 'Filtering',
          description:
            'Removing telemetry that does not provide sufficient operational value.',
        },
        {
          title: 'Retention',
          description:
            'Controlling how long telemetry remains available.',
        },
      ],
    },

    {
      title: 'OpenTelemetry Reliability',
      content:
        'Observability infrastructure should not become a critical failure point for applications. Telemetry pipelines should be designed so that temporary telemetry failures do not unnecessarily stop business traffic. Buffering, batching, local collection, retries, and appropriate resource limits can improve resilience.',
      highlights: [
        {
          title: 'Telemetry pipeline',
          description:
            'The flow of telemetry from applications to observability backends.',
        },
        {
          title: 'Backpressure',
          description:
            'A condition where downstream processing cannot keep up with incoming telemetry.',
        },
        {
          title: 'Resilience',
          description:
            'The ability of telemetry collection to continue or degrade safely during failures.',
        },
      ],
    },

    {
      title: 'What Interviewers Ask',
      content:
        'Common questions include: What is OpenTelemetry? Why use OpenTelemetry instead of directly integrating with a vendor? What is the difference between the OpenTelemetry API and SDK? What is the Collector? What are receivers, processors, and exporters? What is OTLP? How does context propagation work? How would you instrument a microservices or AI application?',
      highlights: [
        {
          title: 'Architecture',
          description:
            'Explain application instrumentation, SDKs, Collector pipelines, and backends.',
        },
        {
          title: 'Vendor neutrality',
          description:
            'Explain why standardized instrumentation reduces dependency on one observability vendor.',
        },
        {
          title: 'Distributed tracing',
          description:
            'Explain trace context propagation across services.',
        },
        {
          title: 'AI observability',
          description:
            'Explain tracing model, retrieval, tool, and provider operations.',
        },
      ],
    },

    {
      title: 'How to Answer in an Interview',
      content:
        'A strong answer is: “OpenTelemetry is a vendor-neutral observability framework for traces, metrics, and logs. I would instrument the application using OpenTelemetry APIs and SDKs, use automatic instrumentation where available, and add manual instrumentation around important business operations. In a larger environment I would use an OpenTelemetry Collector to receive, process, batch, filter, and export telemetry to our observability backend. I would also standardize context propagation across services and control cost through sampling and retention policies. For AI systems, I would trace model calls, retrieval, tools, external providers, latency, and failures.”',
      highlights: [
        {
          title: 'Standardization',
          description:
            'Use consistent telemetry concepts across teams and services.',
        },
        {
          title: 'Collector architecture',
          description:
            'Understand how telemetry is received, processed, and exported.',
        },
        {
          title: 'Business-aware instrumentation',
          description:
            'Instrument important business operations rather than only technical framework calls.',
        },
      ],
    },

    {
      title: 'Common Mistakes',
      content:
        'Common mistakes include thinking OpenTelemetry is only a tracing product, confusing OpenTelemetry with a storage backend, instrumenting everything without controlling telemetry volume, exposing sensitive data in spans, ignoring context propagation, and treating the Collector as mandatory for every architecture.',
      highlights: [
        {
          title: 'Tracing only',
          description:
            'OpenTelemetry covers more than distributed traces.',
        },
        {
          title: 'Backend confusion',
          description:
            'OpenTelemetry generates and transports telemetry; it is not itself a general-purpose long-term observability database.',
        },
        {
          title: 'Uncontrolled telemetry',
          description:
            'Excessive instrumentation can increase cost and operational complexity.',
        },
        {
          title: 'Sensitive data',
          description:
            'Telemetry should not unnecessarily capture confidential information.',
        },
      ],
    },

    {
      title: 'OpenTelemetry for Technical Leaders',
      content:
        'For an AI Engineering Manager, AI Product Manager, Technical Program Manager, or AI Delivery Manager, OpenTelemetry is an observability standard that helps create consistent operational visibility across teams. Leadership responsibilities include defining instrumentation standards, telemetry ownership, privacy rules, sampling policies, Collector architecture, backend strategy, and incident-correlation practices.',
      highlights: [
        {
          title: 'Observability governance',
          description:
            'Define organization-wide standards for telemetry.',
        },
        {
          title: 'Architecture',
          description:
            'Choose appropriate agent, gateway, backend, and export patterns.',
        },
        {
          title: 'Privacy governance',
          description:
            'Ensure telemetry does not expose sensitive customer or business information.',
        },
        {
          title: 'Operational efficiency',
          description:
            'Use standardized telemetry to reduce time spent diagnosing production problems.',
        },
      ],
    },
  ],

  relatedTechnologyIds: [
    'production',
    'observability',
    'monitoring',
    'logging',
    'metrics',
    'distributed-tracing',
    'prometheus',
    'grafana',
    'alerting',
    'incident-management',
    'sli-slo',
    'error-budgets',
    'root-cause-analysis',
    'disaster-recovery',
    'systems',
    'system-design',
    'distributed-systems',
    'microservices',
    'event-driven-systems',
    'queues',
    'kubernetes',
    'docker',
    'aws',
    'azure',
    'google-cloud',
  ],
}

export default opentelemetryKnowledge
