import type { KnowledgeDefinition } from './knowledge'

export const prometheusKnowledge: KnowledgeDefinition = {
  technologyId: 'prometheus',
  slug: 'prometheus',
  title: 'Prometheus',
  summary:
    'Prometheus is an open-source monitoring and alerting system designed around collecting, storing, querying, and evaluating time-series metrics. It is widely used for cloud-native and Kubernetes monitoring.',
  difficulty: 'advanced',

  sections: [
    {
      title: 'What is Prometheus?',
      content:
        'Prometheus is a monitoring system and time-series database. It collects numerical measurements from applications and infrastructure, stores them with timestamps and labels, provides PromQL for querying the data, and supports alerting through its alerting ecosystem.',
      highlights: [
        {
          title: 'Prometheus',
          description:
            'An open-source monitoring and time-series database system.',
        },
        {
          title: 'Time series',
          description:
            'A sequence of timestamped metric values.',
        },
        {
          title: 'PromQL',
          description:
            'Prometheus Query Language used to select, aggregate, and analyze metrics.',
        },
      ],
    },

    {
      title: 'Simple Analogy',
      content:
        'Imagine a security control room with many machines sending numerical readings. Prometheus is like the control room system that regularly collects those readings, stores them with timestamps, and lets operators ask questions such as: How many requests are arriving? What is the error rate? Which server has high CPU? It can also trigger alerts when important conditions occur.',
      highlights: [
        {
          title: 'Sensors',
          description:
            'Represent applications and infrastructure exposing metrics.',
        },
        {
          title: 'Control room',
          description:
            'Represents Prometheus collecting and storing metrics.',
        },
        {
          title: 'Operator query',
          description:
            'Represents PromQL queries used to analyze metrics.',
        },
      ],
    },

    {
      title: 'Why Prometheus Matters',
      content:
        'Modern applications run across many containers, services, nodes, and cloud resources. Prometheus provides a consistent way to collect and query numerical signals from these systems. It is especially useful for service monitoring, Kubernetes, alerting, SLOs, capacity planning, and troubleshooting.',
      highlights: [
        {
          title: 'Monitoring',
          description:
            'Collecting and analyzing operational metrics.',
        },
        {
          title: 'Alerting',
          description:
            'Evaluating metric conditions and producing alerts.',
        },
        {
          title: 'Cloud-native',
          description:
            'Prometheus is widely adopted in containerized and Kubernetes environments.',
        },
      ],
    },

    {
      title: 'Prometheus Architecture',
      content:
        'A typical Prometheus setup includes Prometheus servers, metric targets or exporters, service discovery, PromQL queries, recording rules, alerting rules, and an Alertmanager component for notification routing. Grafana is commonly added for visualization.',
      highlights: [
        {
          title: 'Prometheus server',
          description:
            'Collects and stores metrics and evaluates queries and rules.',
        },
        {
          title: 'Target',
          description:
            'An endpoint from which Prometheus collects metrics.',
        },
        {
          title: 'Exporter',
          description:
            'A component that exposes metrics from a system in a Prometheus-readable format.',
        },
        {
          title: 'Alertmanager',
          description:
            'Routes and manages alerts generated by Prometheus.',
        },
      ],
    },

    {
      title: 'Pull Model',
      content:
        'Prometheus primarily uses a pull model. The Prometheus server periodically scrapes HTTP endpoints exposed by monitored targets and retrieves their current metrics. This gives Prometheus control over collection intervals and target discovery.',
      highlights: [
        {
          title: 'Pull model',
          description:
            'The monitoring server actively retrieves metrics from targets.',
        },
        {
          title: 'Scrape',
          description:
            'A collection operation in which Prometheus retrieves metrics from a target.',
        },
        {
          title: 'Scrape interval',
          description:
            'The frequency at which Prometheus collects metrics from a target.',
        },
      ],
    },

    {
      title: 'Targets',
      content:
        'A target is an endpoint that Prometheus scrapes for metrics. Targets can include applications, Kubernetes services, nodes, databases through exporters, load balancers, and other infrastructure components.',
      highlights: [
        {
          title: 'Target',
          description:
            'A monitored endpoint that exposes metrics.',
        },
        {
          title: 'Target labels',
          description:
            'Metadata identifying characteristics such as service, environment, or instance.',
        },
        {
          title: 'Target health',
          description:
            'Whether Prometheus can successfully scrape the target.',
        },
      ],
    },

    {
      title: 'Metrics Endpoint',
      content:
        'Applications instrumented for Prometheus commonly expose a metrics HTTP endpoint. Prometheus periodically retrieves this endpoint and stores the returned time-series measurements.',
      highlights: [
        {
          title: 'Metrics endpoint',
          description:
            'An HTTP endpoint exposing application metrics.',
        },
        {
          title: 'Instrumentation',
          description:
            'Application code or libraries that generate metrics.',
        },
        {
          title: 'Scraping',
          description:
            'Prometheus retrieving metrics from the endpoint.',
        },
      ],
    },

    {
      title: 'Prometheus Data Model',
      content:
        'Prometheus represents metrics as time series. A time series is identified by a metric name and a set of labels. Each observation has a timestamp and a numerical value.',
      highlights: [
        {
          title: 'Metric name',
          description:
            'The name describing what is being measured.',
        },
        {
          title: 'Label set',
          description:
            'Dimensions that distinguish one time series from another.',
        },
        {
          title: 'Sample',
          description:
            'A numerical value associated with a timestamp.',
        },
      ],
    },

    {
      title: 'Labels',
      content:
        'Labels allow the same metric to be analyzed across dimensions such as service, instance, region, environment, method, or status. Labels make Prometheus flexible, but uncontrolled label values can create high cardinality.',
      highlights: [
        {
          title: 'Label',
          description:
            'A key-value dimension attached to a metric.',
        },
        {
          title: 'Dimension',
          description:
            'An attribute used to group or filter metric data.',
        },
        {
          title: 'High cardinality',
          description:
            'A large number of unique label combinations that can increase storage and query cost.',
        },
      ],
    },

    {
      title: 'PromQL',
      content:
        'PromQL is Prometheus Query Language. It allows engineers to select time series, filter labels, calculate rates, aggregate data, compare values, and create expressions used in dashboards and alerts.',
      highlights: [
        {
          title: 'PromQL',
          description:
            'The query language used to analyze Prometheus metrics.',
        },
        {
          title: 'Selector',
          description:
            'An expression used to select time series.',
        },
        {
          title: 'Aggregation',
          description:
            'Combining multiple time series into meaningful summaries.',
        },
      ],
    },

    {
      title: 'Instant Vector',
      content:
        'An instant vector represents a set of time series containing one sample for each selected series at a particular evaluation time. It is commonly used when querying the current value of metrics.',
      highlights: [
        {
          title: 'Instant vector',
          description:
            'A set of time series with one sample per series at an evaluation point.',
        },
        {
          title: 'Current value',
          description:
            'The latest value available for a selected time series at query evaluation time.',
        },
      ],
    },

    {
      title: 'Range Vector',
      content:
        'A range vector represents a set of time series containing a range of samples over a specified period. Range vectors are commonly used for functions such as rate calculations and historical analysis.',
      highlights: [
        {
          title: 'Range vector',
          description:
            'A set of time series containing samples across a specified time window.',
        },
        {
          title: 'Time window',
          description:
            'The period of historical metric data included in an expression.',
        },
      ],
    },

    {
      title: 'Counter Metrics',
      content:
        'Counters represent cumulative event counts such as total HTTP requests, errors, processed jobs, or messages. PromQL functions such as rate and increase can be used to understand how quickly the counter is changing.',
      highlights: [
        {
          title: 'Counter',
          description:
            'A metric that generally increases as events occur.',
        },
        {
          title: 'rate()',
          description:
            'A PromQL function commonly used to calculate the per-second average increase of a counter over a time range.',
        },
        {
          title: 'increase()',
          description:
            'A PromQL function used to estimate the total increase of a counter over a time range.',
        },
      ],
    },

    {
      title: 'Gauge Metrics',
      content:
        'Gauges represent values that can increase or decrease, such as CPU utilization, active connections, queue depth, or memory usage. They are commonly queried directly or aggregated across instances.',
      highlights: [
        {
          title: 'Gauge',
          description:
            'A metric representing a value that can move up or down.',
        },
        {
          title: 'Current state',
          description:
            'The present value represented by a gauge.',
        },
      ],
    },

    {
      title: 'Histograms',
      content:
        'Prometheus histograms record observations in configurable buckets and also maintain related count and sum information. Histograms are useful for latency and request-duration analysis.',
      highlights: [
        {
          title: 'Histogram',
          description:
            'A metric type used to represent the distribution of observed values.',
        },
        {
          title: 'Bucket',
          description:
            'A configurable upper boundary used to group histogram observations.',
        },
        {
          title: 'Bucket count',
          description:
            'The cumulative number of observations falling within a bucket boundary.',
        },
      ],
    },

    {
      title: 'Histograms and Percentiles',
      content:
        'Prometheus histograms can be used with PromQL functions to estimate percentiles from bucketed observations. This makes them particularly useful for understanding P50, P95, and P99 latency.',
      highlights: [
        {
          title: 'P50',
          description:
            'The median of the observed distribution.',
        },
        {
          title: 'P95',
          description:
            'A percentile representing the upper tail of observed values.',
        },
        {
          title: 'P99',
          description:
            'A percentile highlighting very slow observations.',
        },
      ],
    },

    {
      title: 'Scrape Configuration',
      content:
        'Prometheus configuration defines which targets should be scraped, how frequently they should be collected, and how target metadata should be assigned. In production, service discovery is often used instead of manually maintaining every target.',
      highlights: [
        {
          title: 'Scrape configuration',
          description:
            'Configuration describing how Prometheus collects metrics from targets.',
        },
        {
          title: 'Scrape job',
          description:
            'A logical group of targets sharing common scrape configuration.',
        },
        {
          title: 'Service discovery',
          description:
            'Automatically finding and updating monitored targets.',
        },
      ],
    },

    {
      title: 'Service Discovery',
      content:
        'Dynamic environments such as Kubernetes can create and remove workloads frequently. Service discovery allows Prometheus to discover current targets automatically rather than relying on manually maintained server lists.',
      highlights: [
        {
          title: 'Dynamic discovery',
          description:
            'Automatically discovering changing workloads or endpoints.',
        },
        {
          title: 'Kubernetes discovery',
          description:
            'Using Kubernetes metadata to discover pods, services, nodes, and other targets.',
        },
        {
          title: 'Target lifecycle',
          description:
            'Keeping the monitoring target set aligned with actual infrastructure.',
        },
      ],
    },

    {
      title: 'Exporters',
      content:
        'Exporters expose metrics from systems that do not natively expose Prometheus metrics. Examples include node_exporter for host-level metrics and database-specific exporters for database systems.',
      highlights: [
        {
          title: 'Exporter',
          description:
            'A component that translates or exposes metrics from another system.',
        },
        {
          title: 'node_exporter',
          description:
            'A commonly used exporter for exposing host-level operating-system metrics.',
        },
        {
          title: 'Database exporter',
          description:
            'An exporter that exposes database-related metrics in Prometheus format.',
        },
      ],
    },

    {
      title: 'Recording Rules',
      content:
        'Recording rules precompute frequently used PromQL expressions and store their results as new time series. They can improve dashboard and query performance when expensive calculations are repeatedly evaluated.',
      highlights: [
        {
          title: 'Recording rule',
          description:
            'A rule that evaluates a PromQL expression and stores its result as a metric.',
        },
        {
          title: 'Precomputation',
          description:
            'Calculating expensive expressions ahead of time.',
        },
        {
          title: 'Query performance',
          description:
            'Reducing repeated computation for commonly used expressions.',
        },
      ],
    },

    {
      title: 'Alerting Rules',
      content:
        'Prometheus alerting rules evaluate PromQL expressions and generate alerts when defined conditions remain true. The alert can then be sent to Alertmanager for grouping, routing, inhibition, and notification.',
      highlights: [
        {
          title: 'Alerting rule',
          description:
            'A rule that evaluates a metric condition and creates an alert.',
        },
        {
          title: 'Alert condition',
          description:
            'The PromQL expression that determines whether the alert is active.',
        },
        {
          title: 'Alertmanager',
          description:
            'A service responsible for managing and routing alerts to notification destinations.',
        },
      ],
    },

    {
      title: 'Alertmanager',
      content:
        'Alertmanager is commonly used with Prometheus to handle alerts after they are generated. It can group related alerts, suppress duplicates, apply inhibition rules, and route alerts to channels such as email, chat, or incident-management platforms.',
      highlights: [
        {
          title: 'Grouping',
          description:
            'Combining related alerts into a manageable notification.',
        },
        {
          title: 'Routing',
          description:
            'Sending alerts to the appropriate team or notification destination.',
        },
        {
          title: 'Inhibition',
          description:
            'Suppressing less useful alerts when a higher-level alert already explains the situation.',
        },
      ],
    },

    {
      title: 'Prometheus and Grafana',
      content:
        'Prometheus is commonly used as the metrics collection and storage backend while Grafana provides dashboards and visualization. Grafana queries Prometheus using PromQL and turns the results into charts, tables, and other visualizations.',
      highlights: [
        {
          title: 'Prometheus',
          description:
            'Collects, stores, and queries time-series metrics.',
        },
        {
          title: 'Grafana',
          description:
            'Visualizes metrics and other observability data.',
        },
        {
          title: 'PromQL',
          description:
            'Connects Grafana dashboard queries to Prometheus metrics.',
        },
      ],
    },

    {
      title: 'Prometheus and Kubernetes',
      content:
        'Prometheus is widely used in Kubernetes environments because it can discover dynamic workloads and collect application and platform metrics. Kubernetes monitoring commonly includes nodes, pods, containers, deployments, and application endpoints.',
      highlights: [
        {
          title: 'Kubernetes monitoring',
          description:
            'Collecting cluster, workload, and application metrics.',
        },
        {
          title: 'Pod discovery',
          description:
            'Automatically finding pods that expose metrics.',
        },
        {
          title: 'Cluster visibility',
          description:
            'Using metrics to understand workload and infrastructure health.',
        },
      ],
    },

    {
      title: 'Prometheus and the Four Golden Signals',
      content:
        'Prometheus can collect and calculate metrics representing latency, traffic, errors, and saturation. These signals provide a practical starting point for production service monitoring.',
      highlights: [
        {
          title: 'Latency',
          description:
            'How long requests or operations take.',
        },
        {
          title: 'Traffic',
          description:
            'The amount of workload reaching a service.',
        },
        {
          title: 'Errors',
          description:
            'The number or proportion of failed operations.',
        },
        {
          title: 'Saturation',
          description:
            'How close resources are to their capacity limits.',
        },
      ],
    },

    {
      title: 'Prometheus and SLI / SLO',
      content:
        'Prometheus metrics can be used to calculate Service Level Indicators and evaluate Service Level Objectives. For example, request success metrics can support an availability SLI, while latency histograms can support latency objectives.',
      highlights: [
        {
          title: 'SLI',
          description:
            'A measurable indicator of service behavior.',
        },
        {
          title: 'SLO',
          description:
            'A target level for an SLI.',
        },
        {
          title: 'Error budget',
          description:
            'The amount of unreliability permitted while still meeting an SLO.',
        },
      ],
    },

    {
      title: 'Prometheus and Alert Design',
      content:
        'Prometheus alerts should represent meaningful conditions rather than every metric fluctuation. Good alerts are actionable, have clear severity, contain useful context, and route to an owner who can respond.',
      highlights: [
        {
          title: 'Actionable alert',
          description:
            'An alert that requires a clear operational response.',
        },
        {
          title: 'Severity',
          description:
            'A classification indicating urgency and impact.',
        },
        {
          title: 'Alert ownership',
          description:
            'A clear team or person responsible for responding.',
        },
      ],
    },

    {
      title: 'Prometheus High Cardinality',
      content:
        'High-cardinality labels can create a very large number of time series. Labels such as raw user IDs, request IDs, session IDs, or arbitrary URL paths should generally be avoided unless there is a strong controlled reason to use them.',
      highlights: [
        {
          title: 'Time series explosion',
          description:
            'A rapid increase in the number of unique time series caused by excessive label combinations.',
        },
        {
          title: 'Bounded label',
          description:
            'A label whose possible values remain controlled and predictable.',
        },
        {
          title: 'Cardinality management',
          description:
            'Designing labels and metric dimensions to keep monitoring infrastructure healthy.',
        },
      ],
    },

    {
      title: 'Prometheus Retention',
      content:
        'Prometheus stores time-series data for a configured retention period. Retention decisions should balance investigation requirements, capacity, storage cost, and long-term reporting needs. Long-term storage can be handled using compatible external systems when required.',
      highlights: [
        {
          title: 'Retention',
          description:
            'The period for which Prometheus keeps metric data locally.',
        },
        {
          title: 'Local storage',
          description:
            'The storage used by a Prometheus server for its collected time series.',
        },
        {
          title: 'Long-term storage',
          description:
            'External systems used when metrics need to be retained beyond local Prometheus capacity.',
        },
      ],
    },

    {
      title: 'Prometheus High Availability',
      content:
        'A production monitoring architecture may require multiple Prometheus instances so that monitoring continues even if one monitoring server fails. High availability requires careful consideration of duplicate collection, alert deduplication, storage, and query behavior.',
      highlights: [
        {
          title: 'High availability',
          description:
            'Maintaining monitoring capability despite failure of an individual monitoring component.',
        },
        {
          title: 'Redundant Prometheus',
          description:
            'Multiple Prometheus instances collecting overlapping or complementary metrics.',
        },
        {
          title: 'Alert deduplication',
          description:
            'Preventing redundant Prometheus instances from producing confusing duplicate notifications.',
        },
      ],
    },

    {
      title: 'Prometheus Federation',
      content:
        'Federation allows one Prometheus server to collect selected metrics from another Prometheus server. It can be useful in larger environments where monitoring is distributed across regions, clusters, or organizational boundaries.',
      highlights: [
        {
          title: 'Federation',
          description:
            'Collecting selected metrics from another Prometheus server.',
        },
        {
          title: 'Regional Prometheus',
          description:
            'A Prometheus instance focused on a particular region or environment.',
        },
        {
          title: 'Global Prometheus',
          description:
            'A higher-level Prometheus instance collecting selected aggregated metrics.',
        },
      ],
    },

    {
      title: 'Prometheus Pushgateway',
      content:
        'Prometheus is primarily pull-based, but short-lived jobs can have difficulty being scraped while running. Pushgateway can temporarily expose metrics pushed by batch jobs so Prometheus can scrape them. It should be used selectively rather than as a general replacement for the pull model.',
      highlights: [
        {
          title: 'Pushgateway',
          description:
            'A component that allows certain short-lived jobs to expose pushed metrics for Prometheus scraping.',
        },
        {
          title: 'Batch job',
          description:
            'A workload that starts, performs work, and exits rather than continuously exposing an endpoint.',
        },
        {
          title: 'Selective use',
          description:
            'Push-based collection should be limited to appropriate use cases.',
        },
      ],
    },

    {
      title: 'Prometheus in AI Systems',
      content:
        'Prometheus can monitor AI application metrics such as model request rate, latency, error rate, token usage, provider failures, rate-limit responses, retrieval latency, queue depth, and cost-related measurements. AI-specific application metrics should be combined with infrastructure metrics.',
      highlights: [
        {
          title: 'Model latency',
          description:
            'Time required for an AI model invocation.',
        },
        {
          title: 'Provider errors',
          description:
            'Failures returned by an external AI provider.',
        },
        {
          title: 'Token usage',
          description:
            'The amount of input and output token processing consumed.',
        },
      ],
    },

    {
      title: 'Prometheus for AI Voice',
      content:
        'For an AI voice platform, Prometheus can collect metrics such as active calls, call connection rate, dropped calls, speech-to-text latency, model latency, text-to-speech latency, provider errors, queue depth, and call completion rate.',
      highlights: [
        {
          title: 'Active calls',
          description:
            'The current number of calls being processed.',
        },
        {
          title: 'Dropped call rate',
          description:
            'The rate at which calls terminate unexpectedly.',
        },
        {
          title: 'Voice latency',
          description:
            'The latency between conversational input and system response.',
        },
      ],
    },

    {
      title: 'Prometheus for RAG',
      content:
        'Prometheus can monitor RAG pipeline metrics such as ingestion rate, embedding failures, retrieval latency, vector search requests, model latency, token usage, queue depth, and document-processing throughput.',
      highlights: [
        {
          title: 'Retrieval latency',
          description:
            'Time required to retrieve relevant context.',
        },
        {
          title: 'Embedding failure rate',
          description:
            'The rate at which embedding operations fail.',
        },
        {
          title: 'Ingestion throughput',
          description:
            'The amount of knowledge content processed over time.',
        },
      ],
    },

    {
      title: 'Prometheus Security',
      content:
        'Prometheus and its endpoints should be protected because metrics can reveal architecture, workload, infrastructure, and operational information. Access control, network restrictions, authentication where appropriate, and careful label design are important in production environments.',
      highlights: [
        {
          title: 'Metrics endpoint security',
          description:
            'Protecting endpoints that expose operational metrics.',
        },
        {
          title: 'Access control',
          description:
            'Restricting who can query or administer monitoring data.',
        },
        {
          title: 'Information exposure',
          description:
            'Preventing metric labels and values from unnecessarily revealing sensitive information.',
        },
      ],
    },

    {
      title: 'Prometheus Cost Management',
      content:
        'Prometheus costs are influenced by metric volume, scrape frequency, cardinality, retention, storage, query complexity, and infrastructure size. Teams should monitor the monitoring system itself and remove unnecessary metrics or dimensions.',
      highlights: [
        {
          title: 'Metric volume',
          description:
            'The amount of metric data collected.',
        },
        {
          title: 'Scrape frequency',
          description:
            'How often targets are scraped.',
        },
        {
          title: 'Query cost',
          description:
            'The computational resources required to evaluate metric queries.',
        },
      ],
    },

    {
      title: 'Prometheus Failure Modes',
      content:
        'The monitoring system itself can fail. Possible problems include Prometheus storage exhaustion, scrape failures, target outages, excessive cardinality, expensive queries, network failures, configuration mistakes, and alert-routing failures. Monitoring infrastructure must therefore be monitored too.',
      highlights: [
        {
          title: 'Scrape failure',
          description:
            'Prometheus cannot successfully retrieve metrics from a target.',
        },
        {
          title: 'Storage exhaustion',
          description:
            'The monitoring server runs out of available storage capacity.',
        },
        {
          title: 'Cardinality overload',
          description:
            'Excessive time-series creation causes resource pressure.',
        },
      ],
    },

    {
      title: 'What Interviewers Ask',
      content:
        'Common questions include: What is Prometheus? Why does Prometheus use a pull model? What is PromQL? What are labels? What is cardinality? What are exporters? How does Prometheus work with Grafana? How does Prometheus monitor Kubernetes? What are recording rules and alerting rules? What is Alertmanager? What is federation? How would you use Prometheus for an AI system?',
      highlights: [
        {
          title: 'Prometheus architecture',
          description:
            'Explain targets, scraping, storage, PromQL, rules, and Alertmanager.',
        },
        {
          title: 'Cardinality',
          description:
            'Explain why uncontrolled labels can create operational and cost problems.',
        },
        {
          title: 'Kubernetes',
          description:
            'Explain dynamic target discovery and application/platform monitoring.',
        },
        {
          title: 'AI monitoring',
          description:
            'Explain model, provider, retrieval, latency, usage, and cost metrics.',
        },
      ],
    },

    {
      title: 'How to Answer in an Interview',
      content:
        'A strong answer is: “Prometheus is a time-series monitoring system that primarily uses a pull model. It scrapes metrics from targets, stores them as labeled time series, and provides PromQL for querying and alerting. In a Kubernetes environment I would use service discovery to find dynamic workloads and exporters where necessary for infrastructure metrics. I would use Grafana for visualization and Alertmanager for alert routing. I would be especially careful about cardinality because uncontrolled labels can create a very large number of time series. For AI systems I would add model latency, provider errors, token usage, retrieval latency, and business metrics.”',
      highlights: [
        {
          title: 'Architecture-first answer',
          description:
            'Explain collection, storage, querying, visualization, and alerting as one system.',
        },
        {
          title: 'Operational awareness',
          description:
            'Mention cardinality, retention, high availability, and cost.',
        },
        {
          title: 'Business awareness',
          description:
            'Connect technical metrics with reliability and customer outcomes.',
        },
      ],
    },

    {
      title: 'Common Mistakes',
      content:
        'Common mistakes include assuming Prometheus is only a dashboard tool, confusing Prometheus with Grafana, using unlimited label values, ignoring retention and storage, assuming scraping every metric frequently is free, treating Prometheus as the only observability signal, and exposing monitoring endpoints without appropriate protection.',
      highlights: [
        {
          title: 'Prometheus equals Grafana',
          description:
            'Prometheus collects and stores metrics; Grafana primarily visualizes data.',
        },
        {
          title: 'Unbounded labels',
          description:
            'High-cardinality labels can create excessive time-series volume.',
        },
        {
          title: 'No monitoring of monitoring',
          description:
            'The monitoring platform itself needs health and capacity monitoring.',
        },
        {
          title: 'Metrics only',
          description:
            'Logs and traces are still necessary for detailed investigation.',
        },
      ],
    },

    {
      title: 'Prometheus for Technical Leaders',
      content:
        'For an AI Engineering Manager, AI Product Manager, Technical Program Manager, or AI Delivery Manager, Prometheus is less about memorizing commands and more about understanding the monitoring architecture. A leader should know which services need instrumentation, what signals matter, how SLOs are measured, who owns alerts, how cardinality and cost are controlled, and how monitoring supports incident response and capacity planning.',
      highlights: [
        {
          title: 'Monitoring architecture',
          description:
            'Understand how metrics move from applications and infrastructure into storage, dashboards, and alerts.',
        },
        {
          title: 'Governance',
          description:
            'Define metric standards, ownership, retention, security, and alerting policies.',
        },
        {
          title: 'Reliability leadership',
          description:
            'Use metrics to drive SLOs, incident response, capacity planning, and engineering priorities.',
        },
        {
          title: 'Cost leadership',
          description:
            'Balance monitoring depth with telemetry infrastructure cost.',
        },
      ],
    },
  ],

  relatedTechnologyIds: [
    'production',
    'observability',
    'monitoring',
    'logging',
    'metrics',
    'distributed-tracing',
    'grafana',
    'opentelemetry',
    'alerting',
    'incident-management',
    'sli-slo',
    'error-budgets',
    'root-cause-analysis',
    'disaster-recovery',
    'systems',
    'system-design',
    'distributed-systems',
    'microservices',
    'scalability',
    'capacity-planning',
    'kubernetes',
    'docker',
    'aws',
    'azure',
    'google-cloud',
  ],
}

export default prometheusKnowledge
